### ISSUE TITLE
[ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw

### ISSUE THREAD

**Issue by tstr007** [luanon404/Moe-Moe#3]
Thanks for this great project.
I see this error 
[ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw 
when some content is not visible like videos it play only sound and black screen
and some web games as well
this happens more often than working correctly 

also, onShowCustomView is not called when tapping fullscreen button on videos

one more thing, 
The entry points for the demo folder are 
org.chromium.android_webview.shell.AwShellApplication
org.chromium.android_webview.shell.AwShellActivity

not files in the demo folder itself

Thanks again

**Comment by luanon404** [comment]
- I only copy code from the Chromium build, so I don't know why it's running like that.
- I didn't bump `com.luanon.webview` to 120, so please don't use it now.
- `[ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw` is just a warning. This also occurred in older versions (68-92). So i think It's not a big problem. Also I tested it yesterday, and I can play videos without a black screen. Maybe you can try updating and retrying.
- `onShowCustomView` is not working because I didn't override it. Maybe I will update it later.
> one more thing,
> The entry points for the demo folder are
> org.chromium.android_webview.shell.AwShellApplication
> org.chromium.android_webview.shell.AwShellActivity
>
> not files in the demo folder itself
- I really don't understand what you mean. By default, they named shell, and I won't touch it because I need it. I based it to update `com.luanon.webview`.

**Comment by luanon404** [comment]
im created structure.json, so from now, update will be easier than before

**Comment by luanon404** [comment]
![Screenshot_2023-10-29-10-44-46-59](https://github.com/luanon404/Moe-Moe/assets/71830807/a4d86221-414d-4260-adea-bb9938d0ab23)
![Screenshot_2023-10-29-10-43-40-80](https://github.com/luanon404/Moe-Moe/assets/71830807/93a375b5-86db-4409-a2be-55ae548269f1)

**Comment by luanon404** [comment]
video and alert work as well, just one thing, i need to change layout orientation when click full screen :D

**Comment by luanon404** [comment]
also if u need to ask me something, u can join https://t.me/RHToolCommunity

**Comment by tstr007** [comment]
thank you for your great work

**Comment by luanon404** [comment]
> thank you for your great work

did it work?

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/e9af97d3-1775-4d8a-b96d-ffecd268ead0)

**Comment by luanon404** [comment]
i really dont know should i call AwTestContainerView(context, true)

**Comment by luanon404** [comment]
But if you don't call it, it will get a black screen or content not draw

**Comment by luanon404** [comment]
oh, i found it, its my mistake 
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/5e016bcf-5a98-4de6-b46b-763a311ea6fa)
this should be AwTestContainerView not FrameLayout
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/24463beb-6ed0-4268-9831-e5d65a3d3937)

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/b9465e83-d303-49eb-a4f3-9dfcedd1f43f)
working

**Comment by luanon404** [comment]
com.luanon.webview still black screen when play video and cant enter full screen, idk why chromium example work
